Repository Rebilly/api-definitions, pull requests merged in 2022-10, with the labels that each got.

#1056 Rework invoice descriptions
  openapi/components/parameters/mediaTypeJsonPdf.yaml
  openapi/components/requestBodies/Webhooks/InvoiceAndTransaction.yaml
  openapi/components/requestBodies/Webhooks/InvoiceTaxCalculationFailed.yaml
  openapi/components/requestBodies/Webhooks/TransactionWebhook.yaml
  openapi/components/schemas/Common/CommonInvoice.yaml
  openapi/components/schemas/Coupon/InvoiceDiscount.yaml
  openapi/components/schemas/DayOfWeekLong.yaml
  openapi/components/schemas/InvoiceRetry/AmountAdjustmentInstructions/Policies/DiscountAmountRemaining.yaml
  openapi/components/schemas/InvoiceRetry/AmountAdjustmentInstructions/partial.yaml
  openapi/components/schemas/InvoiceRetry/InvoiceRetryAmountAdjustmentInstruction.yaml
  openapi/components/schemas/InvoiceRetry/InvoiceRetryInstruction.yaml
  openapi/components/schemas/Invoices/Invoice.yaml
  openapi/components/schemas/Invoices/InvoiceIssue.yaml
  openapi/components/schemas/Invoices/InvoiceItem.yaml
  openapi/components/schemas/Invoices/InvoiceReissue.yaml
  openapi/components/schemas/Invoices/InvoiceTax.yaml
  openapi/components/schemas/Invoices/InvoiceTaxItem.yaml
  openapi/components/schemas/Invoices/InvoiceTimeShift.yaml
  openapi/components/schemas/Invoices/InvoiceTransaction.yaml
  openapi/components/schemas/Invoices/TaxTypes/rebilly-taxjar.yaml
  openapi/components/schemas/Organizations/Organization.yaml
  openapi/components/schemas/Organizations/OrganizationSettings.yaml
  openapi/components/schemas/Organizations/TaxLocation.yaml
  openapi/components/schemas/Rules/Actions/schedule-invoice-retry.yaml
  openapi/components/schemas/Scheduling/CommonScheduleInstruction.yaml
  openapi/components/schemas/Scheduling/CustomEventScheduleInstruction.yaml
  openapi/components/schemas/Scheduling/DueTimeShiftInstruction.yaml
  openapi/components/schemas/Scheduling/InvoiceRetryScheduleInstruction.yaml
  openapi/components/schemas/Scheduling/IssueTimeShiftInstruction.yaml
  openapi/components/schemas/Scheduling/Methods/date-interval.yaml
  openapi/components/schemas/Scheduling/Methods/day-of-month.yaml
  openapi/components/schemas/Scheduling/Methods/intelligent.yaml
  openapi/components/schemas/Scheduling/ReminderSchedule.yaml
  openapi/components/schemas/Scheduling/ReminderScheduleInstruction.yaml
  openapi/components/schemas/Scheduling/ServicePeriodAnchorInstruction.yaml
  openapi/components/schemas/Timelines/Actions/redemption-cancel.yaml
  openapi/components/schemas/Timelines/Actions/resend-email.yaml
  openapi/components/schemas/Timelines/Actions/show-edd-search-logs.yaml
  openapi/components/schemas/Timelines/InvoiceTimeline.yaml
  openapi/components/schemas/Timelines/TimelineExtraData.yaml
  openapi/components/schemas/Websites/Website.yaml
  openapi/paths/customers@{id}@upcoming-invoices.yaml
  openapi/paths/invoices.yaml
  openapi/paths/invoices@{id}.yaml
  openapi/paths/invoices@{id}@abandon.yaml
  openapi/paths/invoices@{id}@credit-memo-allocations.yaml
  openapi/paths/invoices@{id}@credit-memo-allocations@{creditMemoId}.yaml
  openapi/paths/invoices@{id}@issue.yaml
  openapi/paths/invoices@{id}@items.yaml
  openapi/paths/invoices@{id}@items@{itemId}.yaml
  openapi/paths/invoices@{id}@recalculate.yaml
  openapi/paths/invoices@{id}@reissue.yaml
  openapi/paths/invoices@{id}@timeline.yaml
  openapi/paths/invoices@{id}@timeline@{messageId}.yaml
  openapi/paths/invoices@{id}@transaction-allocations.yaml
  openapi/paths/invoices@{id}@transaction.yaml
  openapi/paths/invoices@{id}@void.yaml
  openapi/paths/transactions@{id}@timeline@{messageId}.yaml
Labels: Type: Docs

#1064 Update to style to remove word from examples
  WRITING-STYLE.md
Labels: Type: Docs

#1072 Add guidance on possessive apostrophes
  WRITING-STYLE.md
Labels: Type: Docs

#1067 Add boolean examples to writing guide
  WRITING-STYLE.md
Labels: Type: Docs

#1076 Fix incorrect sentence
  WRITING-STYLE.md
Labels: Type: Docs

#1078 Remove aggregationField from histogram transaction report
  openapi/paths/histograms@transactions.yaml
Labels: Type: Bug

#1084 Rework checkout form descriptions
  openapi/components/schemas/CheckoutForm.yaml
  openapi/components/schemas/CheckoutForm/CheckoutFormFixedPlan.yaml
  openapi/components/schemas/CheckoutForm/CheckoutFormVariablePlan.yaml
  openapi/components/schemas/CheckoutForm/CommonCheckoutForm.yaml
  openapi/components/schemas/CheckoutForm/StorefrontCheckoutForm.yaml
  openapi/components/schemas/Common/CommonOrderPreview.yaml
  openapi/components/schemas/ReadyToPay/ReadyToPayItems.yaml
  openapi/components/schemas/Storefront/Purchase.yaml
  openapi/components/schemas/Subscription/OrderItem.yaml
  openapi/paths/checkout-forms.yaml
  openapi/paths/checkout-forms@{id}.yaml
  openapi/paths/storefront/checkout-forms@{id}.yaml
Labels: Type: Docs

#1077 Rework broadcast message descriptions
  openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
  openapi/paths/broadcast-messages.yaml
  openapi/paths/broadcast-messages@{id}.yaml
Labels: Type: Docs

#1090 Rework digital wallet descriptions
  openapi/components/schemas/DigitalWalletCountry.yaml
  openapi/components/schemas/DigitalWalletOnboardingApplePay.yaml
  openapi/components/schemas/PaymentTokens/DigitalWalletValidation/ApplePayValidation.yaml
  openapi/components/schemas/PaymentTokens/DigitalWalletValidation/DigitalWalletValidation.yaml
  openapi/paths/digital-wallets@onboarding@apple-pay.yaml
  openapi/paths/digital-wallets@validation.yaml
Labels: Type: Docs

#1089 Rework data export descriptions
  openapi/components/responses/NoContent.yaml
  openapi/components/schemas/DataExports/DataExport.yaml
  openapi/components/schemas/DataExports/DataExportDateRange.yaml
  openapi/components/schemas/DataExports/resources/customers.yaml
  openapi/components/schemas/DataExports/resources/invoiceItems.yaml
  openapi/components/schemas/DataExports/resources/invoices.yaml
  openapi/components/schemas/DataExports/resources/revenueAudit.yaml
  openapi/components/schemas/DataExports/resources/subscriptions.yaml
  openapi/components/schemas/DataExports/resources/transactions.yaml
  openapi/paths/data-exports.yaml
  openapi/paths/data-exports@{id}.yaml
Labels: Type: Docs

#1088 Update credit memo & timeline descriptions
  openapi/components/requestBodies/Webhooks/CreditMemoWebhook.yaml
  openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
  openapi/components/schemas/CreditMemos/CreditMemoAllocation.yaml
  openapi/components/schemas/Timelines/CreditMemoTimeline.yaml
  openapi/components/schemas/Timelines/CustomerTimeline.yaml
  openapi/components/schemas/Timelines/CustomerTimelineCustomEvent.yaml
  openapi/components/schemas/Timelines/EddTimeline.yaml
  openapi/components/schemas/Timelines/GatewayAccountTimeline.yaml
  openapi/components/schemas/Timelines/OrderTimeline.yaml
  openapi/components/schemas/Timelines/RulesEngineTimeline.yaml
  openapi/components/schemas/Timelines/TimelineExtraData.yaml
  openapi/components/schemas/Timelines/TimelineTable.yaml
  openapi/components/schemas/Timelines/TransactionTimeline.yaml
  openapi/paths/credit-memos.yaml
  openapi/paths/credit-memos@{id}.yaml
  openapi/paths/credit-memos@{id}@timeline.yaml
  openapi/paths/credit-memos@{id}@timeline@{messageId}.yaml
  openapi/paths/credit-memos@{id}@void.yaml
Labels: Type: Docs

#1087 Rework credential descriptions
  openapi/components/parameters/hash.yaml
  openapi/components/schemas/Credentials/Credential.yaml
  openapi/components/schemas/Credentials/EmailCredentials/SmtpAuthorization.yaml
  openapi/components/schemas/Credentials/EmailCredentials/SmtpCredential.yaml
  openapi/components/schemas/Credentials/EmailCredentials/UserPasswordAuthorization.yaml
  openapi/components/schemas/Credentials/ExperianCredentials/ExperianCredential.yaml
  openapi/components/schemas/Credentials/MailgunCredentials/MailgunCredential.yaml
  openapi/components/schemas/Credentials/OAuth2Credentials/GoogleSpreadsheet.yaml
  openapi/components/schemas/Credentials/OAuth2Credentials/OAuth2Credential.yaml
  openapi/components/schemas/Credentials/PatchCredential.yaml
  openapi/components/schemas/Credentials/PlaidCredentials/PlaidCredential.yaml
  openapi/components/schemas/Credentials/PostmarkCredentials/PostmarkCredential.yaml
  openapi/components/schemas/Credentials/SESCredentials/SESCredential.yaml
  openapi/components/schemas/Credentials/SendGridCredentials/SendGridCredential.yaml
  openapi/components/schemas/Credentials/WebhookCredentials/WebhookAuthorization.yaml
  openapi/components/schemas/Credentials/WebhookCredentials/WebhookAuthorization/basic.yaml
  openapi/components/schemas/Credentials/WebhookCredentials/WebhookAuthorization/digest.yaml
  openapi/components/schemas/Credentials/WebhookCredentials/WebhookAuthorization/oauth1.yaml
  openapi/components/schemas/Credentials/WebhookCredentials/WebhookCredential.yaml
  openapi/paths/credential-hashes@aws-ses.yaml
  openapi/paths/credential-hashes@aws-ses@{hash}.yaml
  openapi/paths/credential-hashes@emails.yaml
  openapi/paths/credential-hashes@emails@{hash}.yaml
  openapi/paths/credential-hashes@experian.yaml
  openapi/paths/credential-hashes@experian@{hash}.yaml
  openapi/paths/credential-hashes@mailgun.yaml
  openapi/paths/credential-hashes@mailgun@{hash}.yaml
  openapi/paths/credential-hashes@oauth2.yaml
  openapi/paths/credential-hashes@oauth2@{hash}.yaml
  openapi/paths/credential-hashes@oauth2@{hash}@items.yaml
  openapi/paths/credential-hashes@plaid.yaml
  openapi/paths/credential-hashes@plaid@{hash}.yaml
  openapi/paths/credential-hashes@postmark.yaml
  openapi/paths/credential-hashes@postmark@{hash}.yaml
  openapi/paths/credential-hashes@sendgrid.yaml
  openapi/paths/credential-hashes@sendgrid@{hash}.yaml
  openapi/paths/credential-hashes@taxjar.yaml
  openapi/paths/credential-hashes@taxjar@{hash}.yaml
  openapi/paths/credential-hashes@webhooks.yaml
  openapi/paths/credential-hashes@webhooks@{hash}.yaml
Labels: Type: Docs

#1094 Update fingerprint description
  openapi/components/schemas/RiskMetadata.yaml
Labels: Type: Docs, Type: Bug

#1096 Rework email descriptions
  openapi/components/parameters/systemEventType.yaml
  openapi/components/schemas/EmailDeliverySettings/EmailDeliverySetting.yaml
  openapi/components/schemas/EmailMessages/EmailMessage.yaml
  openapi/components/schemas/EmailNotifications/EmailNotification.yaml
  openapi/components/schemas/EmailNotifications/SendThroughAttribution.yaml
  openapi/paths/email-delivery-setting-verifications@{token}.yaml
  openapi/paths/email-delivery-settings.yaml
  openapi/paths/email-delivery-settings@{id}.yaml
  openapi/paths/email-delivery-settings@{id}@resend-email-verification.yaml
  openapi/paths/email-messages.yaml
  openapi/paths/email-messages@{id}.yaml
  openapi/paths/email-notifications.yaml
  openapi/paths/send-through-attribution@{eventType}.yaml
  openapi/paths/storefront/account@resend-verification.yaml
  openapi/paths/storefront/account@verification@{token}.yaml
Labels: Type: Docs
