Repository Rebilly/api-definitions, pull requests merged in 2022-03, with the labels that each got.

#790 Fix KYC rejections path name
  openapi/openapi.yaml
Labels: bug

#783 Add `archived` status to `KycDocument`
  openapi/components/schemas/Common/CommonKycDocument.yaml
Labels: enhancement

#778 Camel-case KYC settings, rename expiration date
  openapi/components/schemas/KycDocument/IdentityMatches.yaml
  openapi/components/schemas/KycDocument/Settings/KycSettingsIdentity.yaml
  openapi/components/schemas/Organizations/OrganizationSettings.yaml
Labels: enhancement

#799 Add storefront nav item
  openapi/openapi.yaml
  plugins/products-bundler/mapping/Core.yaml
  plugins/products-bundler/mapping/Users.yaml
  plugins/rules/no-unused-tags.js
Labels: documentation

#813 Fixed broken link
  openapi/components/schemas/Timelines/CustomerTimeline.yaml
  openapi/paths/applications.yaml
Labels: bug
