Repository Rebilly/api-definitions, pull requests merged in 2023-09, with the labels that each got.

#1597 Add guidance on acronyms
  WRITING-STYLE.md
Labels: Type: Docs

#1595 fix: Fix Storefront transaction schema
  openapi/components/schemas/StorefrontTransaction.yaml
Labels: Type: Bug

#1601 Add totalTaxAmount setting for Adyen
  openapi/components/schemas/GatewayAccountConfig/Adyen.yaml
Labels: Type: Feature

#1605 Support creditcard and mastercard methods for Wallet88 payment-card
  openapi/components/schemas/GatewayAccountConfig/Wallet88.yaml
Labels: Type: Feature
