Repository Rebilly/api-definitions, pull requests merged in 2023-01, with the labels that each got.

#1197 Update wording of boolean field descriptions
  WRITING-STYLE.md
  openapi/components/schemas/BrowserData.yaml
  openapi/components/schemas/Cashier/CashierStrategyAmounts.yaml
  openapi/components/schemas/CheckoutForm/CommonCheckoutForm.yaml
  openapi/components/schemas/Common/CommonAuthenticationToken.yaml
  openapi/components/schemas/Common/CommonBillingPortal.yaml
  openapi/components/schemas/Common/CommonPlan.yaml
  openapi/components/schemas/Common/CommonProduct.yaml
  openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
  openapi/components/schemas/Common/CommonTransaction.yaml
  openapi/components/schemas/Contact/ContactEmails.yaml
  openapi/components/schemas/Contact/ContactPhoneNumbers.yaml
  openapi/components/schemas/Credentials/PlaidCredentials/PlaidCredential.yaml
  openapi/components/schemas/Customer.yaml
  openapi/components/schemas/CustomerAuthentication/AuthenticationOptions.yaml
  openapi/components/schemas/EmailDeliverySettings/EmailDeliverySetting.yaml
  openapi/components/schemas/Files/File.yaml
  openapi/components/schemas/Files/FileCreateFromInline.yaml
  openapi/components/schemas/Files/FileCreateFromUrl.yaml
  openapi/components/schemas/GatewayAccount.yaml
  openapi/components/schemas/GatewayAccountConfig/Gigadat.yaml
  openapi/components/schemas/GatewayAccountConfig/ParamountInterac.yaml
  openapi/components/schemas/GatewayAccountConfig/Stripe.yaml
  openapi/components/schemas/GatewayAccounts/DigitalWallets.yaml
  openapi/components/schemas/InvoiceRetry/InvoiceRetryAmountAdjustmentInstruction.yaml
  openapi/components/schemas/KycDocument/CreditFileMatches.yaml
  openapi/components/schemas/KycDocument/IdentityMatches.yaml
  openapi/components/schemas/KycRequestDocuments.yaml
  openapi/components/schemas/Membership.yaml
  openapi/components/schemas/PaymentTokens/AlternativePaymentToken.yaml
  openapi/components/schemas/PaymentTokens/BankAccountToken.yaml
  openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
  openapi/components/schemas/PaymentTokens/KhelocardCardToken.yaml
  openapi/components/schemas/PaymentTokens/KlarnaToken.yaml
  openapi/components/schemas/PaymentTokens/PayPalToken.yaml
  openapi/components/schemas/PaymentTokens/PaymentCardToken.yaml
  openapi/components/schemas/PaymentTokens/PlaidAccountToken.yaml
  openapi/components/schemas/Profile.yaml
  openapi/components/schemas/RiskMetadata.yaml
  openapi/components/schemas/Rules/Actions/schedule-invoice-retry.yaml
  openapi/components/schemas/Rules/Rule.yaml
  openapi/components/schemas/Segments/Segment.yaml
  openapi/components/schemas/Subscription/OrderItem.yaml
  openapi/components/schemas/SubscriptionChange.yaml
  openapi/components/schemas/SubscriptionRenewalList.yaml
  openapi/components/schemas/Transactions/ThreeDSecureResult.yaml
  openapi/components/schemas/Transactions/Transaction.yaml
  openapi/components/schemas/UseAsBackup.yaml
  openapi/components/schemas/User.yaml
Labels: Type: Docs

#1215 Fix broken link
  openapi/paths/ready-to-pay.yaml
Labels: Type: Docs

#1216 Rework role descriptions
  openapi/components/schemas/Acl.yaml
  openapi/components/schemas/Embeds/JuniorRolesEmbed.yaml
  openapi/components/schemas/Role.yaml
  openapi/paths/roles.yaml
  openapi/paths/roles@{id}.yaml
Labels: Type: Docs

#1219 Update webhook event descriptions
  openapi/components/requestBodies/Webhooks/ApplicationInstanceDisabled.yaml
  openapi/components/requestBodies/Webhooks/ApplicationInstanceEnabled.yaml
  openapi/components/requestBodies/Webhooks/BalanceTransactionSettled.yaml
  openapi/components/requestBodies/Webhooks/CustomerWebhook.yaml
  openapi/components/requestBodies/Webhooks/DisputeWebhook.yaml
  openapi/components/requestBodies/Webhooks/ExperianCheckPerformed.yaml
  openapi/components/requestBodies/Webhooks/GatewayAccountAndGatewayAccountLimit.yaml
  openapi/components/requestBodies/Webhooks/GatewayAccountWebhook.yaml
  openapi/components/requestBodies/Webhooks/InvoiceAndTransaction.yaml
  openapi/components/requestBodies/Webhooks/InvoiceRevenueRecognized.yaml
  openapi/components/requestBodies/Webhooks/InvoiceTaxCalculationFailed.yaml
  openapi/components/requestBodies/Webhooks/InvoiceWebhook.yaml
  openapi/components/requestBodies/Webhooks/KycDocumentWebhook.yaml
  openapi/components/requestBodies/Webhooks/MergedCustomer.yaml
  openapi/components/requestBodies/Webhooks/PaymentCardWebhook.yaml
  openapi/components/requestBodies/Webhooks/PaymentInstrumentWebhook.yaml
  openapi/components/requestBodies/Webhooks/RenewalInvoiceIssued.yaml
  openapi/components/requestBodies/Webhooks/SubscriptionAndSubscriptionPause.yaml
  openapi/components/requestBodies/Webhooks/SubscriptionWebhook.yaml
  openapi/components/requestBodies/Webhooks/TransactionWebhook.yaml
  openapi/components/schemas/GlobalWebhookEventType.yaml
Labels: Type: Docs

#1217 Rework search and send through
  openapi/components/schemas/Common/CommonOrder.yaml
  openapi/components/schemas/Search.yaml
  openapi/components/schemas/ShippingRates/ShippingOption.yaml
  openapi/components/schemas/ShippingRates/ShippingRate.yaml
  openapi/components/schemas/Signup.yaml
  openapi/components/schemas/Status.yaml
  openapi/components/schemas/Subscription/OrderItem.yaml
  openapi/components/schemas/Subscription/UpcomingInvoiceItem.yaml
  openapi/paths/search.yaml
  openapi/paths/send-through-attribution@{eventType}.yaml
  openapi/paths/shipping-rates.yaml
  openapi/paths/shipping-rates@{id}.yaml
Labels: Type: Docs

#1222 Rework tags descriptions
  openapi/components/parameters/tag.yaml
  openapi/components/schemas/Tags/Tag.yaml
  openapi/paths/tags.yaml
  openapi/paths/tags@{tag}.yaml
  openapi/paths/tags@{tag}@customers.yaml
  openapi/paths/tags@{tag}@customers@{customerId}.yaml
  openapi/paths/tags@{tag}@kyc-documents.yaml
  openapi/paths/tags@{tag}@kyc-documents@{kycDocumentId}.yaml
Labels: Type: Docs

#1231 Update links
  openapi/components/parameters/collectionExpand.yaml
  openapi/components/parameters/collectionFilter.yaml
  openapi/components/schemas/GatewayAccount.yaml
  openapi/components/schemas/GlobalWebhook.yaml
  openapi/components/schemas/PaymentInstruments/ValueObjects/VaultedInstrument.yaml
  openapi/components/schemas/ReadyToPay/ReadyToPayMethodFilters.yaml
  openapi/components/schemas/ResourceCustomFields.yaml
  openapi/components/schemas/Rules/Bind.yaml
  openapi/components/schemas/ShippingTypes/RebillyShipping.yaml
  openapi/description.md
  openapi/openapi.yaml
  openapi/paths/ready-to-pay.yaml
  openapi/paths/reports@revenue-audit.yaml
  openapi/paths/storefront/ready-to-pay.yaml
Labels: Type: Docs

#1225 Rework tracking descriptions
  openapi/components/schemas/Tracking/ApiTracking.yaml
  openapi/components/schemas/Tracking/SubscriptionTracking.yaml
  openapi/components/schemas/Tracking/WebhookTracking.yaml
  openapi/paths/tracking@api.yaml
  openapi/paths/tracking@api@{id}.yaml
  openapi/paths/tracking@lists.yaml
  openapi/paths/tracking@webhooks.yaml
  openapi/paths/tracking@webhooks@{id}.yaml
  openapi/paths/tracking@webhooks@{id}@resend.yaml
Labels: Type: Docs

#1224 Rework token descriptions
  openapi/components/schemas/Common/CommonAuthenticationToken.yaml
  openapi/components/schemas/PaymentTokens/AlternativePaymentToken.yaml
  openapi/components/schemas/PaymentTokens/BankAccountToken.yaml
  openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
  openapi/components/schemas/PaymentTokens/KhelocardCardToken.yaml
  openapi/components/schemas/PaymentTokens/KlarnaToken.yaml
  openapi/components/schemas/PaymentTokens/PayPalToken.yaml
  openapi/components/schemas/PaymentTokens/PaymentCardToken.yaml
  openapi/components/schemas/PaymentTokens/PlaidAccountToken.yaml
  openapi/components/schemas/ResetPasswordToken.yaml
  openapi/openapi.yaml
  openapi/paths/authentication-tokens@{token}.yaml
  openapi/paths/authentication-tokens@{token}@exchange.yaml
  openapi/paths/tokens.yaml
  openapi/paths/tokens@{token}.yaml
Labels: Type: Docs

#1227 Rework transaction descriptions
  openapi/components/schemas/PurchaseBumps/PurchaseBumpOffer.yaml
  openapi/components/schemas/PurchaseBumps/PurchaseBumpSplitVersion.yaml
  openapi/components/schemas/PurchaseBumps/PurchaseBumpSplitVersionName.yaml
  openapi/components/schemas/PurchaseBumps/PurchaseBumpStatus.yaml
  openapi/components/schemas/TransactionRefund.yaml
  openapi/components/schemas/Transactions/Transaction.yaml
  openapi/components/schemas/Transactions/TransactionNotificationUrl.yaml
  openapi/components/schemas/Transactions/TransactionQuery.yaml
  openapi/components/schemas/Transactions/TransactionRedirectUrl.yaml
  openapi/components/schemas/Transactions/TransactionRequest.yaml
  openapi/components/schemas/Transactions/TransactionUpdate.yaml
  openapi/paths/transactions.yaml
  openapi/paths/transactions@{id}.yaml
  openapi/paths/transactions@{id}@query.yaml
  openapi/paths/transactions@{id}@refund.yaml
  openapi/paths/transactions@{id}@timeline.yaml
  openapi/paths/transactions@{id}@timeline@{messageId}.yaml
  openapi/paths/transactions@{id}@update.yaml
Labels: Type: Docs

#1229 Rework usages, users, webhooks, and website descriptions
  openapi/components/schemas/GlobalWebhook.yaml
  openapi/components/schemas/ProfileMfa.yaml
  openapi/components/schemas/Rules/WebhookHeader.yaml
  openapi/components/schemas/Usage.yaml
  openapi/paths/storefront/websites@{id}.yaml
  openapi/paths/usages@{id}.yaml
  openapi/paths/users.yaml
  openapi/paths/users@{id}.yaml
  openapi/paths/users@{id}@mfa.yaml
  openapi/paths/users@{id}@totp-reset.yaml
  openapi/paths/webhooks.yaml
  openapi/paths/webhooks@{id}.yaml
  openapi/paths/websites.yaml
  openapi/paths/websites@{id}.yaml
Labels: Type: Docs

#1234 Move text to KYC documents
  openapi/openapi.yaml
Labels: Type: Docs, Type: Bug

#1232 Update intro sections
  openapi/description.md
  openapi/openapi.yaml
  plugins/products-bundler/mapping/Users.yaml
Labels: Type: Docs

#1230 Update ID usage
  openapi/components/parameters/applicationId.yaml
  openapi/components/parameters/customerId.yaml
  openapi/components/parameters/kycDocumentId.yaml
  openapi/components/requestBodies/Webhooks/ApplicationInstanceDisabled.yaml
  openapi/components/requestBodies/Webhooks/ApplicationInstanceEnabled.yaml
  openapi/components/requestBodies/Webhooks/DisputeWebhook.yaml
  openapi/components/schemas/ApiKeyScope.yaml
  openapi/components/schemas/Applications/Application.yaml
  openapi/components/schemas/Blocklist.yaml
  openapi/components/schemas/CheckoutForm/CommonCheckoutForm.yaml
  openapi/components/schemas/Common/CommonAuthenticationToken.yaml
  openapi/components/schemas/Common/CommonBillingPortal.yaml
  openapi/components/schemas/Coupon/Coupon.yaml
  openapi/components/schemas/Coupon/CouponRedemption.yaml
  openapi/components/schemas/Customer.yaml
  openapi/components/schemas/CustomerAuthentication/CustomerJWT.yaml
  openapi/components/schemas/CustomerCredential.yaml
  openapi/components/schemas/Dispute.yaml
  openapi/components/schemas/Invoices/InvoiceItem.yaml
  openapi/components/schemas/Rules/Actions/create-infusionsoft-order.yaml
  openapi/components/schemas/Rules/Actions/create-infusionsoft-payment.yaml
  openapi/components/schemas/Rules/Actions/create-intuit-quickbooks-balance-transaction-entry.yaml
  openapi/components/schemas/Rules/Actions/create-intuit-quickbooks-payment.yaml
  openapi/components/schemas/Rules/Actions/create-intuit-quickbooks-refund-receipt.yaml
  openapi/components/schemas/Rules/Actions/create-intuit-quickbooks-revenue-recognition-entry.yaml
  openapi/components/schemas/Rules/Actions/send-email.yaml
  openapi/components/schemas/Rules/Actions/tag-or-untag-customer.yaml
  openapi/components/schemas/Rules/Actions/update-intuit-quickbooks-invoice.yaml
  openapi/components/schemas/Rules/Actions/void-intuit-quickbooks-invoice.yaml
  openapi/paths/api-keys@{id}.yaml
  openapi/paths/application-instances@{applicationId}.yaml
  openapi/paths/applications@{id}.yaml
  openapi/paths/applications@{id}@instances.yaml
  openapi/paths/applications@{id}@instances@{organizationId}.yaml
  openapi/paths/billing-portals@{id}.yaml
  openapi/paths/broadcast-messages@{id}.yaml
  openapi/paths/checkout-forms@{id}.yaml
  openapi/paths/credit-memos@{id}.yaml
  openapi/paths/custom-domains@{domain}.yaml
  openapi/paths/custom-fields@{resource}@{name}.yaml
  openapi/paths/customer-timeline-custom-events@{id}.yaml
  openapi/paths/customers@{customerId}@summary-metrics.yaml
  openapi/paths/customers@{id}.yaml
  openapi/paths/customers@{id}@edd-score.yaml
  openapi/paths/customers@{id}@edd-search-results.yaml
  openapi/paths/customers@{id}@edd-search-results@{searchResultId}.yaml
  openapi/paths/customers@{id}@lead-source.yaml
  openapi/paths/customers@{id}@timeline@{messageId}.yaml
  openapi/paths/disputes@{id}.yaml
  openapi/paths/invoices@{id}.yaml
  openapi/paths/invoices@{id}@abandon.yaml
  openapi/paths/invoices@{id}@issue.yaml
  openapi/paths/invoices@{id}@items.yaml
  openapi/paths/invoices@{id}@recalculate.yaml
  openapi/paths/invoices@{id}@reissue.yaml
  openapi/paths/invoices@{id}@timeline@{messageId}.yaml
  openapi/paths/invoices@{id}@void.yaml
  openapi/paths/shipping-rates@{id}.yaml
  openapi/paths/storefront/checkout-forms@{id}.yaml
  openapi/paths/storefront/orders@{id}.yaml
Labels: Type: Docs

#1248 Update cancellation description
  openapi/paths/subscription-cancellations@{id}.yaml
Labels: Type: Docs

#1260 Fix invalid operation IDs
  openapi/paths/customers@{id}@aml.yaml
  openapi/paths/customers@{id}@edd-search-results.yaml
  openapi/paths/customers@{id}@edd-search-results@{searchResultId}.yaml
  openapi/paths/email-delivery-settings@{id}.yaml
  openapi/paths/events@{eventType}@timeline.yaml
  openapi/paths/events@{eventType}@timeline@{messageId}.yaml
Labels: Type: Bug

#1261 Add edd search results path
  openapi/openapi.yaml
Labels: Type: Bug
