Repository Rebilly/api-definitions, pull requests merged in 2024-01, with the labels that each got.

#1737 fix(dependancy): Override typesense axios version
  package-lock.json
  package.json
Labels: dependencies

#1731 Update references and readme
  README.md
  openapi/components/parameters/collectionExpand.yaml
  openapi/components/parameters/collectionFilter.yaml
  openapi/components/parameters/subscriptionExpand.yaml
  openapi/components/requestBodies/PostDepositRequest.yaml
  openapi/components/schemas/ApplicationInstance.yaml
  openapi/components/schemas/Bind.yaml
  openapi/components/schemas/BroadcastMessage.yaml
  openapi/components/schemas/DepositRequest.yaml
  openapi/components/schemas/DepositStrategy.yaml
  openapi/components/schemas/FlexiblePlan.yaml
  openapi/components/schemas/GatewayAccount.yaml
  openapi/components/schemas/GlobalWebhook.yaml
  openapi/components/schemas/OneTimeSale.yaml
  openapi/components/schemas/OriginalPlan.yaml
  openapi/components/schemas/ReadyToPayMethodFilters.yaml
  openapi/components/schemas/ReadyToPayoutMethodFilters.yaml
  openapi/components/schemas/RebillyShipping.yaml
  openapi/components/schemas/ResourceCustomFields.yaml
  openapi/components/schemas/RulesEmailNotification.yaml
  openapi/components/schemas/StorefrontOneTimeSale.yaml
  openapi/components/schemas/StorefrontSubscription.yaml
  openapi/components/schemas/Subscription.yaml
  openapi/components/schemas/VaultedInstrument.yaml
  openapi/description.md
  openapi/openapi.yaml
  openapi/paths/ready-to-pay.yaml
  openapi/paths/reports@revenue-audit.yaml
  openapi/paths/storefront/ready-to-pay.yaml
  openapi/paths/storefront/ready-to-payout.yaml
  plugins/products-bundler/mapping/Users.yaml
Labels: Type: Docs

#1740 fix: Add missing security to Storefront operations
  openapi/paths/storefront/deposit-strategies@{id}.yaml
  openapi/paths/storefront/plans.yaml
  openapi/paths/storefront/plans@{id}.yaml
  openapi/paths/storefront/products.yaml
  openapi/paths/storefront/products@{id}.yaml
  openapi/paths/storefront/ready-to-pay.yaml
  openapi/paths/storefront/ready-to-payout.yaml
Labels: Type: Bug

#1744 fix: Make _links of plan schemas read only
  openapi/components/schemas/OneTimeSalePlan.yaml
  openapi/components/schemas/SubscriptionOrderPlan.yaml
  openapi/components/schemas/TrialOnlyPlan.yaml
Labels: Type: Bug
